### ISSUE TITLE
Got error running npm start

### ISSUE THREAD

**Issue by malcolmocean** [stevenxie/tailguard#2]
Not sure at all what's going on here. I did `npm install` and that worked fine.

Maybe my version of node is too old? (v10.14.2)

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/malcolm/.nvm/versions/node/v10.14.2/bin/node',
1 verbose cli   '/home/malcolm/.nvm/versions/node/v10.14.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.10.3
3 info using node@v10.14.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tailguard@0.0.0~prestart: tailguard@0.0.0
6 info lifecycle tailguard@0.0.0~start: tailguard@0.0.0
7 verbose lifecycle tailguard@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle tailguard@0.0.0~start: PATH: /home/malcolm/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/malcolm/dev/tailguard/node_modules/.bin:/home/malcolm/.nvm/versions/node/v10.14.2/bin:/usr/local/heroku/bin:/home/malcolm/bin:/usr/local/bin:/home/malcolm/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle tailguard@0.0.0~start: CWD: /home/malcolm/dev/tailguard
10 silly lifecycle tailguard@0.0.0~start: Args: [ '-c', 'lerna run --parallel start' ]
11 silly lifecycle tailguard@0.0.0~start: Returned: code: 2  signal: null
12 info lifecycle tailguard@0.0.0~start: Failed to exec start script
13 verbose stack Error: tailguard@0.0.0 start: `lerna run --parallel start`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/malcolm/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/malcolm/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid tailguard@0.0.0
15 verbose cwd /home/malcolm/dev/tailguard
16 verbose Linux 4.15.0-96-generic
17 verbose argv "/home/malcolm/.nvm/versions/node/v10.14.2/bin/node" "/home/malcolm/.nvm/versions/node/v10.14.2/bin/npm" "start"
18 verbose node v10.14.2
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 2
22 error tailguard@0.0.0 start: `lerna run --parallel start`
22 error Exit status 2
23 error Failed at the tailguard@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by malcolmocean** [comment]
(Tried with newer version of node and that didn't help)
